# Generated by Django 5.2.1 on 2025-05-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('owner', 'Owner'), ('professional', 'Professional'), ('group_team', 'Group/Team')], default='professional', max_length=20),
        ),
    ]
