# Generated by Django 5.2.1 on 2025-05-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('organizer', 'Organizer'), ('owner', 'Owner'), ('professional', 'Professional'), ('group_team', 'Group/Team')], default='user', max_length=20),
        ),
    ]
