# Generated by Django 4.2 on 2025-05-29 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0008_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="availability",
            field=models.TextField(blank=True, null=True, verbose_name="Availability"),
        ),
        migrations.AddField(
            model_name="profile",
            name="capacity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Max Capacity"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="drink_menu",
            field=models.JSONField(blank=True, null=True, verbose_name="Drink Menu"),
        ),
        migrations.AddField(
            model_name="profile",
            name="gallery",
            field=models.JSONField(blank=True, null=True, verbose_name="Gallery"),
        ),
        migrations.AddField(
            model_name="profile",
            name="menu",
            field=models.JSONField(blank=True, null=True, verbose_name="Menu/Pricing"),
        ),
        migrations.AddField(
            model_name="profile",
            name="opening_hours",
            field=models.TextField(blank=True, null=True, verbose_name="Opening Hours"),
        ),
        migrations.AddField(
            model_name="profile",
            name="organizer_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Organizer Description"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="portfolio_url",
            field=models.URLField(blank=True, null=True, verbose_name="Portfolio URL"),
        ),
        migrations.AddField(
            model_name="profile",
            name="rental_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Rental Price (€)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="specialization",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Specialization"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="team_leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="team_members",
            field=models.ManyToManyField(
                blank=True, related_name="teams_joined", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="team_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Group Name"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="venue_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Venue Name"
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
