# Generated by Django 4.2 on 2025-06-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_availability_profile_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='advanced_role_selected_once',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
