# Generated by Django 4.2 on 2025-02-05 04:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("fecha", models.DateTimeField()),
                ("aforo", models.IntegerField()),
                ("descripcion", models.TextField()),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="eventos/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comprador", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "hash",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("pagado", models.BooleanField(default=False)),
                ("qr_code", models.ImageField(blank=True, upload_to="qrcodes/")),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.evento"
                    ),
                ),
            ],
        ),
    ]
