# Generated by Django 4.2 on 2025-02-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_entrada_telefono"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrada",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="entrada",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
        ),
    ]
