# Generated by Django 4.2 on 2025-02-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_entrada_precio_alter_entrada_qr_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entrada",
            name="precio",
        ),
        migrations.AlterField(
            model_name="entrada",
            name="qr_code",
            field=models.ImageField(blank=True, default=1, upload_to="qrcodes/"),
            preserve_default=False,
        ),
    ]
