# Generated by Django 4.2 on 2025-02-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_remove_entrada_precio_alter_entrada_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrada",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
