# Generated by Django 4.2 on 2025-02-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0005_entrada_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrada",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
        ),
    ]
