# Generated by Django 4.2 on 2025-02-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0006_alter_entrada_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="evento",
            name="ubicacion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="entrada",
            name="precio",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
