# Generated by Django 4.2 on 2025-02-09 03:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0007_evento_precio_evento_ubicacion_alter_entrada_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
