# Generated by Django 4.2 on 2025-02-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0008_alter_evento_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
