# Generated by Django 4.2 on 2025-02-09 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0011_evento_uuid_id_alter_evento_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
